name: foodgram workflow

on: [push]

jobs: 
  build_and_push_to_docker_hub:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      # STEP 1
      - name: Check out the repo
        uses: actions/checkout@v3
      # STEP 2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1 
      # STEP 3
      - name: Login to Docker 
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 
          password: ${{ secrets.DOCKER_PASSWORD }} 
      # STEP 4
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2 
        with:
          context: backend/
          push: true
          tags: mspiridonov/foodgram_backend:latest

  send_message:
    name: Send message from telegram bot
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    # STEP 1
    - name: send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: ${{ github.workflow }} успешно выполнен!